server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order Part
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: Delivery Part
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**, 
        - id: Product Stock Part
          uri: http://localhost:8083
          predicates:
            - Path=/inventories/**, 
        - id: Customercenter
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order Part
          uri: http://orderPart:8080
          predicates:
            - Path=/orders/**, 
        - id: Delivery Part
          uri: http://deliveryPart:8080
          predicates:
            - Path=/deliveries/**, 
        - id: Product Stock Part
          uri: http://productStockPart:8080
          predicates:
            - Path=/inventories/**, 
        - id: Customercenter
          uri: http://customercenter:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
