---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Order Part
  labels:
    app: Order Part
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Order Part
  template:
    metadata:
      labels:
        app: Order Part
    spec:
      containers:
        - name: Order Part
          image: username/Order Part:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Delivery Part
  labels:
    app: Delivery Part
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Delivery Part
  template:
    metadata:
      labels:
        app: Delivery Part
    spec:
      containers:
        - name: Delivery Part
          image: username/Delivery Part:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Product Stock Part
  labels:
    app: Product Stock Part
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Product Stock Part
  template:
    metadata:
      labels:
        app: Product Stock Part
    spec:
      containers:
        - name: Product Stock Part
          image: username/Product Stock Part:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Customercenter
  labels:
    app: Customercenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Customercenter
  template:
    metadata:
      labels:
        app: Customercenter
    spec:
      containers:
        - name: Customercenter
          image: username/Customercenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Order Part
  labels:
    app: Order Part
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Order Part


---


apiVersion: v1
kind: Service
metadata:
  name: Delivery Part
  labels:
    app: Delivery Part
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Delivery Part


---


apiVersion: v1
kind: Service
metadata:
  name: Product Stock Part
  labels:
    app: Product Stock Part
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Product Stock Part


---


apiVersion: v1
kind: Service
metadata:
  name: Customercenter
  labels:
    app: Customercenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Customercenter

